version: '3.8'

services:
  php_cli:
    build:
      dockerfile: Dockerfile
      context: ./docker/php_cli/build
    container_name: php_cli
    environment:
      - DEV=0
#    command: bash -c "composer install && php LetsRoll.php"
    command: php LetsRoll.php
    volumes:
      - ./:/usr/src/application
    working_dir: /usr/src/application
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "1000"